Upgraded design of press page and tested it
evan01/assetdesigns pull request #30
Opened 2018-02-12 02:58 UTC by puranik9

# Issue
Closes #11 

#Changes in this pull request
- Did a full redesign of the press page
- Displays images and text in a grid layout (as requested by Tessa)

#Screenshot or Gif of the pull request
<img width="1276" alt="screen shot 2018-02-11 at 9 57 21 pm" src="https://user-images.githubusercontent.com/8695013/36082348-a11ce506-0f76-11e8-9b69-32d013baf568.png">

2018-02-12 15:33 UTC, evan01 requested changes
So while the theme is good, on the actual website, you pasted all of the code inline. There's no styling...

2018-02-14 03:14 UTC, assetdesigns commented
The press page isnt displayed on the assetdesigns dev, and I don't see the grid format in this screenshot.

2018-02-16 14:57 UTC, evan01 submitted a review, later dismissed

2018-02-16 15:17 UTC, cvauclair approved these changes

2018-02-16 15:17 UTC, merged