41 create test database form
evan01/assetdesigns pull request #58
Opened 2018-03-10 18:58 UTC by cvauclair

# Issue NUMBER(ON WAFFLE)
Closes #ISSUENUMBER

#Changes in this pull request

#Screenshot or Gif of the FEATURE/THEME CHANGE/ OR VISUAL CHANGE

2018-03-10 20:57 UTC, evan01 requested changes
Please attach a picture/gif showing what your changes look like. Also make sure to reference the waffle issue you are closing. Looks great though!

2018-03-10 20:57 UTC, evan01 commented on exampleShopifyApp/app.rb
> +require 'shopify_api'
this should not be committed!

2018-03-10 20:57 UTC, evan01 commented on exampleShopifyApp/views/database_test_form.erb
> +<html>
exampleShopifyApp/* should also not be merged

2018-03-11 19:14 UTC, cvauclair commented
Added screenshots of the admin urls
![screenshot from 2018-03-11 15-11-57](https://user-images.githubusercontent.com/3653954/37257368-d7b7abfe-253e-11e8-8131-17be50e13e52.png)
![screenshot from 2018-03-11 15-11-53](https://user-images.githubusercontent.com/3653954/37257369-d7d55abe-253e-11e8-819e-610bdd703a99.png)
![screenshot from 2018-03-11 15-11-45](https://user-images.githubusercontent.com/3653954/37257370-d7ed0e98-253e-11e8-8aae-1d13d5551d38.png)
![screenshot from 2018-03-11 15-11-36](https://user-images.githubusercontent.com/3653954/37257371-d801789c-253e-11e8-874b-f2d84dfdecbb.png)
![screenshot from 2018-03-11 15-11-29](https://user-images.githubusercontent.com/3653954/37257372-d81372d6-253e-11e8-85f7-402dfaa2990e.png)
![screenshot from 2018-03-11 15-10-24](https://user-images.githubusercontent.com/3653954/37257373-d82c2ad8-253e-11e8-9774-4defa1a5aea1.png)

2018-03-11 20:06 UTC, the-luantran commented
Is it that necessary to have to add the Lat and Long coordinates? It doesn't feel user-friendly...I feel like the user should only have to add an address, and then we can either process that through an API before inserting into the DB. Or I could also process it after the GET request (not ideal tho)

2018-03-11 22:04 UTC, evan01 approved these changes

2018-03-11 22:04 UTC, merged